added custom blurb code
blurb/jekyll-multiple-languages-plugin pull request #1
Opened 2016-10-20 09:38 UTC by ivanskof

2016-10-20 16:10 UTC, chicagoing requested changes

2016-10-20 16:10 UTC, chicagoing commented on lib/jekyll-multiple-languages-plugin.rb
> +        # Custom Blurb code: Removed to reduce noise
You can remove lines 350 & 351.

2016-10-20 16:10 UTC, chicagoing commented on lib/jekyll-multiple-languages-plugin.rb
> +      self.config['default_lang_only'] ||= []
I don't see this being used anywhere. Should we remove it for now?

2016-10-21 08:44 UTC, ivanskof commented
@chicagoing changes done

2016-10-21 15:03 UTC, chicagoing approved these changes
+1

2016-10-21 15:03 UTC, chicagoing commented
Looks good. Merge when you're ready. Thank you.

2016-10-24 06:46 UTC, ivanskof commented
@lpeacock @chicagoing I can't merge, I don't have write access.

2016-10-24 15:14 UTC, merged